### ISSUE TITLE
Get dashboards hosted somewhere

### ISSUE THREAD

**Issue by miketaylr** [mozilla/top-sites-dashboards#4]

**Comment by johngian** [comment]
I drafted some top sites dashboards here:
https://webcompat-kibana.herokuapp.com/app/kibana#/dashboards

Specifically:

* Top sites generic dashboard with aggregations from webcompat and bugzilla issues
* Top sites webcompat bar charts charts
  * open issues
  * needsdiagnosis issues
  * severitycritical issues
  * sitewait issues
  * combination of all the above 

Let me know what you think
